version: "2"
services:
  web:
    # Use the special reloop image:
    image: "datawire/reloopd"
    ports:
      - "5000:5000"
    volumes:
      # Mount the repository as /hello, read-only
      - ".:/hello:ro"
    environment:
      # The file or directory to watch for updates:
      RELOOP_WATCH: "/hello"
      # Run once as setup:
      RELOOP_BEFORE_CMD: "pip install -r /hello/requirements.txt"
      # Run every time the watched files change:
      RELOO_CMD: "python /hello/hello.py"
  mydatabase:
    # The postgres dependency for hello.py:
    image: "postgres"
