version: "2"
services:
  web:
    # Use the special reloop image:
    image: "datawire/reloopd"
    ports:
      - "5000:5000"
    volumes:
      # Mount the repository as /hello, read-only
      - ".:/code:ro"
    environment:
      # The file or directory to watch for updates:
      RELOOP_WATCH: "/code"
      # Run once as setup:
      RELOOP_BEFORE_CMD: "pip install -r /code/requirements.txt"
      # Run every time the watched files change:
      RELOOP_CMD: "python /code/hello/hello.py"
    depends_on:
      - mydatabase
  mydatabase:
    # The postgres dependency for hello.py:
    image: "postgres"
