---
sudo: false
dist: trusty
lang: python
services:
  - docker

env:
  global:
  - DOCKER_REPO=datawire/reloopdDND
  - COMMIT=${TRAVIS_COMMIT::8}

install:
- pip install tox-travis
- make ci-setup
- pip3 install -r ci-tools/requirements.txt

script:
- ./travis.sh
